name: fleet_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.7.0
  flutter_screenutil: 
  google_fonts:
  responsive_framework: ^1.5.1
  flutter_svg: 
  form_field_validator: ^1.1.0
  logger: ^2.5.0
  get_ip_address:
  device_info_plus: ^11.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  geolocator_web: ^4.1.1
  shimmer: 
  file_picker: ^5.3.1
  intl:
  dio_smart_retry: ^6.0.0
  mime_type: ^1.0.0
  path_provider: 
  image_picker_for_web: ^3.0.6
  cross_file: ^0.3.4+2
  shared_preferences: 
  image_network: ^2.6.0
  firebase_core: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
