// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV4AGm8zFa7x3O6EMZBeOWSG6aOjRORE0',
    appId: '1:293859958098:web:64ef62796d2a94f587ee8b',
    messagingSenderId: '293859958098',
    projectId: 'fleet-3294a',
    authDomain: 'fleet-3294a.firebaseapp.com',
    storageBucket: 'fleet-3294a.firebasestorage.app',
    measurementId: 'G-6L00FDDHH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx11GtYn6-701ISz_LIh7Ig8Kxvpqu7WU',
    appId: '1:293859958098:android:eb6df7cfaa28cba287ee8b',
    messagingSenderId: '293859958098',
    projectId: 'fleet-3294a',
    storageBucket: 'fleet-3294a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB64VGAHhaz47BCWn9CsegeGp-6dQgfKO8',
    appId: '1:293859958098:ios:40311f159169bcab87ee8b',
    messagingSenderId: '293859958098',
    projectId: 'fleet-3294a',
    storageBucket: 'fleet-3294a.firebasestorage.app',
    iosBundleId: 'com.fleet.fleetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB64VGAHhaz47BCWn9CsegeGp-6dQgfKO8',
    appId: '1:293859958098:ios:40311f159169bcab87ee8b',
    messagingSenderId: '293859958098',
    projectId: 'fleet-3294a',
    storageBucket: 'fleet-3294a.firebasestorage.app',
    iosBundleId: 'com.fleet.fleetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV4AGm8zFa7x3O6EMZBeOWSG6aOjRORE0',
    appId: '1:293859958098:web:1fa526c9d467312b87ee8b',
    messagingSenderId: '293859958098',
    projectId: 'fleet-3294a',
    authDomain: 'fleet-3294a.firebaseapp.com',
    storageBucket: 'fleet-3294a.firebasestorage.app',
    measurementId: 'G-145XLHXL39',
  );
}
